config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  devise_for :users, :controllers => {:registrations => "registrations"}
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :jobs, only: [ :index, :show ]
  get 'chooseajob', to: 'jobschoices#index', as: :jobschoices
  get 'chooseastudy', to: 'studieschoices#index', as: :studieschoices
  get 'autres_etudes', to: 'studieschoices#autres_etudes'
  get 'etudes_arts_et_design', to: 'studieschoices#etudes_arts_et_design'
  get 'batiment_et_travaux_publics', to: 'studieschoices#etudes_batiment_et_travaux_publics'
  get 'etudes_commerce_et_gestion', to: 'studieschoices#etudes_commerce_et_gestion'
  get 'etudes_droit', to: 'studieschoices#etudes_droit'
  get 'etudes_banque_et_assurance', to: 'studieschoices#etudes_banque_et_assurance'
  get 'etudes_environnement', to: 'studieschoices#etudes_environnement'
  get 'etudes_industrie', to: 'studieschoices#etudes_industrie'
  get 'etudes_communication_et_journalisme', to: 'studieschoices#etudes_communication_et_journalisme'
  get 'etudes_informatique_et_electronique', to: 'studieschoices#etudes_informatique_et_electronique'
  get 'etudes_medical_et_paramedical', to: 'studieschoices#etudes_medical_et_paramedical'
  get 'etudes_tourisme_hotellerie_et_restauration', to: 'studieschoices#etudes_tourisme_hotellerie_et_restauration'
  get 'etudes_specialisees', to: 'studieschoices#etudes_specialisees'
  get 'etudes_social_et_psychologie', to: 'studieschoices#etudes_social_et_psychologie'
  get 'etudes_ingenieur', to: 'studieschoices#etudes_ingenieur'
  patch "jobs/:id/like", to: "jobs#like", as: :like
  patch "jobs/:id/dislike", to: "jobs#dislike", as: :dislike
  get 'favorites', to: 'pages#favorites'
  get 'signupstudents', to: 'pages#signupstudents'
  get 'test', to: 'pages#test'
  get 'signupparents', to: 'pages#signupparents'
  get 'homepage', to: 'pages#homepage'
  get 'homepage_parents', to: 'pages#homepage_parents'
  get 'suggestion', to: 'pages#suggestion'
  get 'infos', to: 'pages#infos'
  get 'ose', to: 'pages#ose'
  get 'temoignage1', to: 'pages#temoignage1'
  get 'temoignage2', to: 'pages#temoignage2'
  get 'temoignage3', to: 'pages#temoignage3'
  get 'temoignage4', to: 'pages#temoignage4'
  get 'entretien', to: 'pages#entretien'
  get 'conseillers', to: 'pages#conseillers'
  get 'financements', to: 'pages#financements'
  get 'bourse', to: 'pages#bourse'
  get 'apl', to: 'pages#apl'
  get 'CGU', to: 'pages#CGU'
  get 'Mentions_legales', to: 'pages#Mentions_legales'
  get 'Contact', to: 'pages#Contact'
  get 'outils', to: 'pages#outils'
  get 'changements', to: 'pages#changements'
  get 'un_cv_parfait', to: 'pages#un_cv_parfait'
  get 'lettre_de_motivation_qui_cartonne', to: 'pages#lettre_de_motivation_qui_cartonne'
  get 'je_vais_tout_dechirer', to: 'pages#je_vais_tout_dechirer'
  get 'je_sors_du_lot', to: 'pages#je_sors_du_lot'
  get 'bourse_et_APL', to: 'pages#bourse_et_APL'
  get 'les_autres_aides', to: 'pages#les_autres_aides'
  get 'le_pret_bancaire', to: 'pages#le_pret_bancaire'
  get 'tout_savoir_sur_orientation', to: 'pages#tout_savoir_sur_orientation'
  get 'epanouissement_au_quotidien', to: 'pages#epanouissement_au_quotidien'
  get 'energies_que_je_transmets', to: 'pages#energies_que_je_transmets'
  get 'devenir_mentor', to: 'pages#devenir_mentor'
  get 'send_friend_request', to: 'networks#send_friend_request'
  get 'network', to: 'networks#network'
  get 'messenger', to: 'networks#messenger'
  get 'users_all', to: 'networks#users_all'
  get 'aideslogement', to: 'pages#aideslogement'
  get 'aidesregionales', to: 'pages#aidesregionales'
  get 'aidespourpartir', to: 'pages#aidespourpartir'
  get 'aidestransports', to: 'pages#aidestransports'
  get 'aidesmaster', to: 'pages#aidesmaster'
  get 'aidespremieremploi', to: 'pages#aidespremieremploi'
  get 'aidesartistes', to: 'pages#aidesartistes'
  get 'aidesmerite', to: 'pages#aidesmerite'
  get 'aidesurgences', to: 'pages#aidesurgences'
  get 'aidesautres', to: 'pages#aidesautres'
  get 'dropdown_HDF', to: 'pages#dropdown_HDF'
  get 'dropdown_IDF', to: 'pages#dropdown_IDF'
  get 'dropdown_Normandie', to: 'pages#dropdown_Normandie'
  get 'dropdown_Bretagne', to: 'pages#dropdown_Bretagne'
  get 'dropdown_PDLL', to: 'pages#dropdown_PDLL'
  get 'dropdown_CVDL', to: 'pages#dropdown_CVDL'
  get 'dropdown_BFC', to: 'pages#dropdown_BFC'
  get 'dropdown_GE', to: 'pages#dropdown_GE'
  get 'dropdown_NA', to: 'pages#dropdown_NA'
  get 'dropdown_ARA', to: 'pages#dropdown_ARA'
  get 'dropdown_Occitanie', to: 'pages#dropdown_Occitanie'
  get 'dropdown_PACA', to: 'pages#dropdown_PACA'
  get 'dropdown_Paradis_francais', to: 'pages#dropdown_Paradis_francais'

  resources :interests, only: [ :index, :show, :edit ]
  patch "interests/:id/likeinterest", to: "interests#likeinterest", as: :likeinterest
  patch "interests/:id/dislikeinterest", to: "interests#dislikeinterest", as: :dislikeinterest
  patch "interests/:id/like2interest", to: "interests#like2interest", as: :like2interest
  patch "interests/:id/dislike2interest", to: "interests#dislike2interest", as: :dislike2interest
  get 'meslikes', to: 'interests#meslikes'

  get 'myprofile', to: 'users#edit'
  patch 'edit_profile', to: 'users#update'
  get 'search', to: 'users#search'
  post 'unblock_friend', to: 'networks#unblock_friend'
  post 'accept_friend', to: 'networks#accept_friend'
  post 'decline_friend', to: 'networks#decline_friend'
  post 'request_friend', to: 'networks#request_friend'
  post 'block_friend', to: 'networks#block_friend'
  post 'remove_friend', to: 'networks#remove_friend'
  get 'search_friends', to: 'users#search_friends'

  resources :users do
    get :autocomplete_user_name, :on => :collection
  end

  resources :conversations do
    resources :messages
  end
end

app/controllers/networks_controller.rb
class NetworksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_friendable, only: [:unblock_friend, :accept_friend, :decline_friend, :request_friend, :block_friend, :remove_friend]


  def network
    @results = User.where(user_category: "student") - User.where(first_name: nil) - Array(current_user.blocked_friends) - Array(current_user) - current_user.friends.paginate(:page => params[:page], :per_page => 100)
    job_likes_ids = current_user.job_likes.pluck(:votable_id)
    @commun_jobs_results = []
    @results.each_with_index do |result, index|
      array = result.job_likes.pluck(:votable_id)
      @commun_jobs_results << [result, (job_likes_ids & array).empty? ? nil : Job.find( (job_likes_ids & array)[0]).name ,(job_likes_ids & array).size - 1]
      break if @commun_jobs_results.size == 10 && !params[:more]
    end
    @results = @commun_jobs_results
  end

  def messenger
    @conversations = Conversation.where(sender_id: current_user.id) + Conversation.where(recipient_id: current_user.id)
    @conversations = nil if @conversations.empty?
  end

  def send_friend_request
    friendable = User.find(params[:friendable])
    current_user.friend_request(friendable)
    redirect_to :network
  end

  def users_all
    @friends = current_user.friends
    set_friends_clusters
  end

  # NETWORK FRIENDS ACTIONS

  def request_friend
    current_user.friend_request(@friend) if @friend
    respond_to do |format|
      format.js { render "networks/request_friend", friend_id: @friend.id }
    end
  end

  # USERS FRIENDS ACTIONS

  def unblock_friend
    if @friend
      current_user.unblock_friend(@friend)
      current_user.friend_request(@friend)
      @friend.accept_request(current_user)
    end
    set_friends_clusters
    respond_to do |format|
      format.js { render "users_all" }
    end
  end

  def accept_friend
    current_user.accept_request(@friend) if @friend
    set_friends_clusters
    respond_to do |format|
      format.js { render "users_all" }
    end
  end

  def decline_friend
    current_user.decline_request(@friend) if @friend
    set_friends_clusters
    respond_to do |format|
      format.js { render "users_all" }
    end
  end

  def block_friend
    current_user.block_friend(@friend) if @friend
    set_friends_clusters
    respond_to do |format|
      format.js { render "users_all" }
    end
  end

  def remove_friend
    current_user.remove_friend(@friend) if @friend
    set_friends_clusters
    respond_to do |format|
      format.js { render "users_all" }
    end
  end

  private

  # SETTERS

  def set_friends_clusters
    User.joins(:friendships).eager_load!(:friendships)
    @requested_friends = current_user.requested_friends.empty? ? nil : current_user.requested_friends
    @blocked_friends = current_user.blocked_friends.empty? ? nil : current_user.blocked_friends
    #@suggested_friends = User.all - Array(@blocked_friends) - current_user.friends - Array(current_user)
    @pending_friends = current_user.pending_friends.empty? ? nil : current_user.pending_friends
  end

  def set_friendable
    @friend = User.find(params[:friendable].to_i) if params[:friendable]
  end

  # STRONG PARAMS

  def conversation_params
   params.permit(:sender_id, :recipient_id)
  end

  def message_params
    params.require(:message).permit(:body, :user_id)
  end


end

app/views/networks/_search.html.erb
<form id="live-search-form" method="get" action="<%= search_path %>">
  <input id="big-search-box" name="query" type="text" placeholder="Recherche un étudiant ici..."/>

</form>


<script type="text/javascript">

  $("#big-search-box").bind("keyup", function() {

  var form = $("#live-search-form");

  var url = "/search";
  var formData = form.serialize();
  $.get(url, formData, function(html) {

    $("#container-homepage").html(html);

  });

});
</script>

app/views/networks/_search_friends.html.erb
<form id="live-search-form-friends" method="get" action="<%= search_friends_path %>">
  <input id="big-search-box-friends" name="query" type="text" placeholder="Recherche un de tes contacts ici..."/>

</form>


<script type="text/javascript">

  $("#big-search-box-friends").bind("keyup", function() {

  var form = $("#live-search-form-friends");

  var url = "/search_friends";
  var formData = form.serialize();
  $.get(url, formData, function(html) {

    $("#users_all").html(html);

  });

});
</script>

app/views/networks/messenger.html.erb
<div class="container-extra">
<%= render 'shared/navbar' %>
  <div class="navbar-onglet-network">
    <div class="navbar-onglet-item row">
      <a class="col-xs-4" href="/network"><i class="fas fa-user-plus"></i></a>
      <a class="col-xs-4 active" href="/messenger"><i class="far fa-envelope"></i></a>
      <a class="col-xs-4" href="/users_all"><i class="fas fa-users"></i></a>
    </div>
  </div>

<!-- CODE ICI -->

<% if @conversations && current_user.first_name && !current_user.first_name.empty? && current_user.last_name && !current_user.last_name.empty? %>

  <!-- FRIENDS INDEX -->

  <div>
    <h2 class="title-network2">Mes conversations:</h2>
    <div class="cards-homepage">
      <div class="row row-homepage">
        <% @conversations.each do |conversation| %>

          <% user = conversation.sender_id == current_user.id ? conversation.recipient : conversation.sender %>
          <%= link_to conversation_messages_path(conversation) do %>

            <div class="col-xs-12">
              <div class="card-network">
                <img src=<%= (user.avatar_url.nil? ? 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=c0ff296c4f785350505c2b5545ae7393&auto=format&fit=crop&w=1650&q=80' : user.avatar_url)%> alt="profile" class="profile img-network">
                <p class="name-user">
                  <%= "#{user.first_name} #{user.last_name}" %>
                </p>
                <p class="message-user"><%= conversation.messages.last.body[0..140] if !conversation.messages.empty? && conversation.messages.first.body %></p>
              </div>
            </div>

          <% end %>
        <% end %>

      </div>
    </div>
  </div>

<% elsif !@conversations %>

  <!-- EMPTY CONVERSATIONS GESTION -->

  <div>
    <p class="accroche-students2">N'attends plus une seule seconde pour demander à tes nouveaux contacts des infos sur les études et les métiers qui te plaisent ! Par exemple: "est-ce que tu sais quelle est la date limite pour envoyer les dossiers d'inscription?" 👍</p>
    <%= link_to "Mes contacts", users_all_path, class:"btn btn-primary students-network" %>
  </div>

<% else %>
  <%= render "shared/edit_profile_suggestion" %>
<% end %>

</div>

<!-- FIN PARTIE CODE -->

<%= render '/shared/navigationbar' %>

app/views/networks/network.html.erb
<div class="container-extra">
<%= render 'shared/navbar' %>
  <%# if current_user.first_name.nil? %>

  <%# else %>
  <div class="navbar-onglet-network">
    <div class="navbar-onglet-item row">
      <a class="col-xs-4 active" href="/network"><i class="fas fa-user-plus"></i></a>
      <a class="col-xs-4" href="/messenger"><i class="far fa-envelope"></i></a>
      <a class="col-xs-4" href="/users_all"><i class="fas fa-users"></i></a>
    </div>
  </div>

<!-- PARTIE MODIFIABLE -->

<% if current_user.first_name && !current_user.first_name.empty? && current_user.last_name && !current_user.last_name.empty? %>

    <div class="container-homepage" id="container-homepage">

      <!-- USERS RESEARCH -->

      <%= render "networks/search", results: @results %>

      <!-- CONTACTS SUGGESTIONS -->

      <%= render "networks/searchable_users/users_index" %>

    </div>

<% else %>
  <%= render "shared/edit_profile_suggestion" %>
<% end %>
</div>
  <!-- FIN DE PARTIE MODIFIABLE -->
<%= render '/shared/navigationbar' %>

app/views/networks/request_friend.js.erb
function refreshDiv(outerHTML) {
  const job = document.getElementById(<%= @friend.id %>);
  job.outerHTML = outerHTML;
}

refreshDiv('<%= j render('networks/searchable_users/user_card', user: @friend, work: nil) %>');

app/views/networks/users_all.html.erb
<div class="container-extra">
<%= render 'shared/navbar' %>

  <div class="navbar-onglet-network">
    <div class="navbar-onglet-item row">
      <a class="col-xs-4" href="/network"><i class="fas fa-user-plus"></i></a>
      <a class="col-xs-4" href="/messenger"><i class="far fa-envelope"></i></a>
      <a class="col-xs-4 active" href="/users_all"><i class="fas fa-users"></i></a>
    </div>
  </div>


<!-- CODE ICI -->

  <%= render "networks/users_all/index" %>


<!-- FIN PARTIE CODE -->


</div>
<%= render '/shared/navigationbar' %>

app/views/networks/users_all.js.erb
function refreshDiv(outerHTML) {
  const job = document.getElementById("users_all");
  job.outerHTML = outerHTML;
}

refreshDiv('<%= j render('networks/users_all/index') %>');