config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  devise_for :users, :controllers => {:registrations => "registrations"}
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :jobs, only: [ :index, :show ]
  get 'chooseajob', to: 'jobschoices#index', as: :jobschoices
  get 'chooseastudy', to: 'studieschoices#index', as: :studieschoices
  get 'autres_etudes', to: 'studieschoices#autres_etudes'
  get 'etudes_arts_et_design', to: 'studieschoices#etudes_arts_et_design'
  get 'batiment_et_travaux_publics', to: 'studieschoices#etudes_batiment_et_travaux_publics'
  get 'etudes_commerce_et_gestion', to: 'studieschoices#etudes_commerce_et_gestion'
  get 'etudes_droit', to: 'studieschoices#etudes_droit'
  get 'etudes_banque_et_assurance', to: 'studieschoices#etudes_banque_et_assurance'
  get 'etudes_environnement', to: 'studieschoices#etudes_environnement'
  get 'etudes_industrie', to: 'studieschoices#etudes_industrie'
  get 'etudes_communication_et_journalisme', to: 'studieschoices#etudes_communication_et_journalisme'
  get 'etudes_informatique_et_electronique', to: 'studieschoices#etudes_informatique_et_electronique'
  get 'etudes_medical_et_paramedical', to: 'studieschoices#etudes_medical_et_paramedical'
  get 'etudes_tourisme_hotellerie_et_restauration', to: 'studieschoices#etudes_tourisme_hotellerie_et_restauration'
  get 'etudes_specialisees', to: 'studieschoices#etudes_specialisees'
  get 'etudes_social_et_psychologie', to: 'studieschoices#etudes_social_et_psychologie'
  get 'etudes_ingenieur', to: 'studieschoices#etudes_ingenieur'
  patch "jobs/:id/like", to: "jobs#like", as: :like
  patch "jobs/:id/dislike", to: "jobs#dislike", as: :dislike
  get 'favorites', to: 'pages#favorites'
  get 'signupstudents', to: 'pages#signupstudents'
  get 'test', to: 'pages#test'
  get 'signupparents', to: 'pages#signupparents'
  get 'homepage', to: 'pages#homepage'
  get 'homepage_parents', to: 'pages#homepage_parents'
  get 'suggestion', to: 'pages#suggestion'
  get 'infos', to: 'pages#infos'
  get 'ose', to: 'pages#ose'
  get 'temoignage1', to: 'pages#temoignage1'
  get 'temoignage2', to: 'pages#temoignage2'
  get 'temoignage3', to: 'pages#temoignage3'
  get 'temoignage4', to: 'pages#temoignage4'
  get 'entretien', to: 'pages#entretien'
  get 'conseillers', to: 'pages#conseillers'
  get 'financements', to: 'pages#financements'
  get 'bourse', to: 'pages#bourse'
  get 'apl', to: 'pages#apl'
  get 'CGU', to: 'pages#CGU'
  get 'Mentions_legales', to: 'pages#Mentions_legales'
  get 'Contact', to: 'pages#Contact'
  get 'outils', to: 'pages#outils'
  get 'changements', to: 'pages#changements'
  get 'un_cv_parfait', to: 'pages#un_cv_parfait'
  get 'lettre_de_motivation_qui_cartonne', to: 'pages#lettre_de_motivation_qui_cartonne'
  get 'je_vais_tout_dechirer', to: 'pages#je_vais_tout_dechirer'
  get 'je_sors_du_lot', to: 'pages#je_sors_du_lot'
  get 'bourse_et_APL', to: 'pages#bourse_et_APL'
  get 'les_autres_aides', to: 'pages#les_autres_aides'
  get 'le_pret_bancaire', to: 'pages#le_pret_bancaire'
  get 'tout_savoir_sur_orientation', to: 'pages#tout_savoir_sur_orientation'
  get 'epanouissement_au_quotidien', to: 'pages#epanouissement_au_quotidien'
  get 'energies_que_je_transmets', to: 'pages#energies_que_je_transmets'
  get 'devenir_mentor', to: 'pages#devenir_mentor'
  get 'send_friend_request', to: 'networks#send_friend_request'
  get 'network', to: 'networks#network'
  get 'messenger', to: 'networks#messenger'
  get 'users_all', to: 'networks#users_all'
  get 'aideslogement', to: 'pages#aideslogement'
  get 'aidesregionales', to: 'pages#aidesregionales'
  get 'aidespourpartir', to: 'pages#aidespourpartir'
  get 'aidestransports', to: 'pages#aidestransports'
  get 'aidesmaster', to: 'pages#aidesmaster'
  get 'aidespremieremploi', to: 'pages#aidespremieremploi'
  get 'aidesartistes', to: 'pages#aidesartistes'
  get 'aidesmerite', to: 'pages#aidesmerite'
  get 'aidesurgences', to: 'pages#aidesurgences'
  get 'aidesautres', to: 'pages#aidesautres'
  get 'dropdown_HDF', to: 'pages#dropdown_HDF'
  get 'dropdown_IDF', to: 'pages#dropdown_IDF'
  get 'dropdown_Normandie', to: 'pages#dropdown_Normandie'
  get 'dropdown_Bretagne', to: 'pages#dropdown_Bretagne'
  get 'dropdown_PDLL', to: 'pages#dropdown_PDLL'
  get 'dropdown_CVDL', to: 'pages#dropdown_CVDL'
  get 'dropdown_BFC', to: 'pages#dropdown_BFC'
  get 'dropdown_GE', to: 'pages#dropdown_GE'
  get 'dropdown_NA', to: 'pages#dropdown_NA'
  get 'dropdown_ARA', to: 'pages#dropdown_ARA'
  get 'dropdown_Occitanie', to: 'pages#dropdown_Occitanie'
  get 'dropdown_PACA', to: 'pages#dropdown_PACA'
  get 'dropdown_Paradis_francais', to: 'pages#dropdown_Paradis_francais'

  resources :interests, only: [ :index, :show, :edit ]
  patch "interests/:id/likeinterest", to: "interests#likeinterest", as: :likeinterest
  patch "interests/:id/dislikeinterest", to: "interests#dislikeinterest", as: :dislikeinterest
  patch "interests/:id/like2interest", to: "interests#like2interest", as: :like2interest
  patch "interests/:id/dislike2interest", to: "interests#dislike2interest", as: :dislike2interest
  get 'meslikes', to: 'interests#meslikes'

  get 'myprofile', to: 'users#edit'
  patch 'edit_profile', to: 'users#update'
  get 'search', to: 'users#search'
  post 'unblock_friend', to: 'networks#unblock_friend'
  post 'accept_friend', to: 'networks#accept_friend'
  post 'decline_friend', to: 'networks#decline_friend'
  post 'request_friend', to: 'networks#request_friend'
  post 'block_friend', to: 'networks#block_friend'
  post 'remove_friend', to: 'networks#remove_friend'
  get 'search_friends', to: 'users#search_friends'

  resources :users do
    get :autocomplete_user_name, :on => :collection
  end

  resources :conversations do
    resources :messages
  end
end

app/models/job.rb
class Job < ApplicationRecord
  # searchkick language: "english", match: :word_start
  mount_uploader :photo, PhotoUploader
  acts_as_votable
  has_many :job_interests
  has_many :job_sectors
  has_many :interests, through: :job_interests
  has_many :sectors, through: :job_sectors


  # include AlgoliaSearch

  # index = Algolia::Index.new('jobs')

  # index.set_settings(
  #   searchableAttributes: [
  #     'name'
  #   ]
  # )

  include PgSearch
  pg_search_scope :search_by_full_name, against: [:name, :synonym],
    using: {
      tsearch: {
            prefix: true,
            negation: true,
            highlight: {
              start_sel: '<b>',
              stop_sel: '</b>',
            }
          }
        }
        pg_search_scope :gringo_search,
                          :against => :word,
                          :ignoring => :accents
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!

  def index
    @interests = Interest.all
    if params[:query]
      @jobs = Job.search_by_full_name(params[:query]).with_pg_search_highlight.paginate(:page => params[:page], :per_page => 100)
    else
      @jobs = Job.all.paginate(:page => params[:page], :per_page => 100)
      @interests = Interest.all
    end

  end


  def show
    @jobb = Job.find(params[:id])
  end

  def like
    @job = Job.find(params[:id])
    if @job.liked_by current_user
      respond_to do |format|
        format.html { redirect_to jobs_path }
        format.js
      end
    end
  end

  def like2
    @jobb = Job.find(params[:id])
    if @jobb.liked_by current_user
      respond_to do |format|
        format.html { redirect_to jobs_path }
        format.js
      end
    end
  end

  def dislike
    @job = Job.find(params[:id])
    if @job.disliked_by current_user
      respond_to do |format|
        format.html { redirect_to jobs_path }
        format.js
      end
    end
  end

  def dislike2
    @jobb = Job.find(params[:id])
    if @jobb.disliked_by current_user
      respond_to do |format|
        format.html { redirect_to jobs_path }
        format.js
      end
    end
  end

  def job_params
    params.require(:job).permit(:name)
  end


end

app/views/jobs/_autocomplete.html.erb
<div class="autocomplete-results">
  <%= job.name %>
</div>

app/views/jobs/_card.html.erb
<div class="card" id= <%= "#{job.id}" %>>
  <div ><%= cl_image_tag job.photo, :class => "card__image" %></div>
  <div class="card__content">
    <div class="card__title">
      <h2><%= link_to job.name, job_path(job) %></h2>
      <%= link_to "", job_path(job), class: "card-link"%>
      <% if job.get_likes.where(voter_id: current_user).count == 0 %>
        <%= link_to like_path(job), remote: true, method: :patch, class: "card-like-link" do%>
          <i class="far fa-heart"></i>
        <% end %>
      <% else %>
        <%= link_to dislike_path(job), remote: true, method: :patch, class: "card-like-link" do %>
          <i class="fas fa-heart"></i>
        <% end %>
      <% end %>
    </div>
    <div class="card__text">
      <p><%= link_to job.short_description.first(98), job_path(job) %>...</p>
    </div>
  </div>
</div>

app/views/jobs/_filter.html.erb
<div class="filter-box">
  <div id="filter-title">
     <% if params[:interests] %>
       <%= link_to "Effacer filtres", jobs_path %>
     <% elsif %>
       Filtrer par:
     <% end %>
   </div>
   <div class="dropdown">
     <button class="btn form-control dropdown-toggle font-15 height-30" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" style="font-weight: lighter;
  font-size: 16px;">
       <%= params[:interests].present? ? params[:interests] : "Secteurs" %>
       <span class="caret"></span>
     </button>
     <ul class="dropdown-menu small-font" aria-labelledby="dropdownMenu1">
       <% @interests.each do |interest| %>
         <li><%= link_to "#{interest.name}", jobs_path(interests: "#{interest}") %></li>
       <% end %>
       <!-- <li role="separator" class="divider"></li> -->
     </ul>
   </div>
</div>

app/views/jobs/_likeshow.html.erb
<div id= <%= "#{@jobb.id}" %>>
  <% if @jobb.get_likes.where(voter_id: current_user).count == 0 %>
    <%= link_to like_path(@jobb), remote: true, method: :patch, class: "" do%>
      <i class="far fa-heart"></i>
    <% end %>
  <% else %>
    <%= link_to dislike_path(@jobb), remote: true, method: :patch, class: "" do %>
      <i class="fas fa-heart"></i>
    <% end %>
  <% end %>
</div>

app/views/jobs/_search.html.erb
<%= form_tag jobs_path, method: :get do %>
  <%= text_field_tag :query, params[:query], class: "form-control search", placeholder: "Trouve un métier ici..." %>
<% end %>

app/views/jobs/dislike.js.erb
function refreshCard(outerHTML) {
  const job = document.getElementById(<%= @job.id %>);
  job.outerHTML = outerHTML;
}

refreshCard('<%= j render "jobs/card", job:@job %>');

app/views/jobs/index.html.erb
<div class="navbar-up">

    <% if user_signed_in? %>
      <div class="navbar-up-item">
        <i class=" back fas fa-chevron-left" onclick="history.back(-1)"></i>
        <a type="student-btn" href="/favorites" class="btn btn-primary next-step-btn-small">Voir mes favoris <i class="fas fa-arrow-right arrow-next-step"></i></a>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-up-item navbar-up-link" %>
    <% end %>
</div>
<div class="container">

  <!-- [...] -->
    <%= render 'jobs/search' %>

<!-- the list of movies -->

<%#= render '/jobs/filter' %>

  <div class="cards">
    <div class="row">
      <% @jobs.each do |job| %>
        <div class="col-xs-6 col-md-3">
          <div class="card" id= <%= "#{job.id}" %>>
            <div ><%= link_to (cl_image_tag job.photo, :class => "card__image"), job_path(job) %></div>
            <div class="card__content">
              <div class="card__title">
                <li>
                  <h2><%= link_to job.name, job_path(job) %></h2>
                </li>
                <%= link_to "", job_path(job), class: "card-link"%>
                <% if job.get_likes.where(voter_id: current_user).count == 0 %>
                  <%= link_to like_path(job), remote: true, method: :patch, class: "card-like-link" do%>
                    <i class="far fa-heart"></i>
                  <% end %>
                <% else %>
                  <%= link_to dislike_path(job), remote: true, method: :patch, class: "card-like-link" do %>
                    <i class="fas fa-heart"></i>
                  <% end %>
                <% end %>
              </div>
              <div class="card__text">
                <p><%= link_to job.short_description.first(98), job_path(job) %>...</p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="pagination" style="font-size: 20px;">
    <div class="row">
      <div class="col-xs-10 col-xs-offset-1">
        <%= will_paginate @posts %>
      </div>
    </div>
  </div>
</div>


<%= render '/shared/navigationbar' %>

app/views/jobs/like.js.erb
function refreshCard(outerHTML) {
  const job = document.getElementById(<%= @job.id %>);
  job.outerHTML = outerHTML;
}

refreshCard('<%= j render "jobs/card", job:@job %>');

app/views/jobs/show.html.erb
<%= render 'shared/navbar' %>
<div class="show_job_img"><%= cl_image_tag @jobb.photo, :class => "banner__image" %></div>
<div class="container-showjob">
   <div class="col-xs-9">
    <h1 class="namejobs"><%= @jobb.name %></h1>
    <h3 class="shortjobs"><%= @jobb.short_description %></h3>
    <div class="sidebar-box">
      <p class="descjobs"><%= @jobb.description %></p>
    </div>
  </div>
   <div class="col-xs-2 icon">
    <p style='font-size: 10px; margin-left: -8px; margin-right: -16px; font-style: italic; text-align: center; margin-top: 15px;'>Clique sur les icônes <span style="font-size: 20px; font-style: normal; margin-left: 1px;">😎</span></p>
    <a href="#" data-container="body" data-toggle="popover" data-placement="left" style="top: 40px;
    left: 31px; position: absolute;" data-content="<h6><strong>Salaire:</strong></h6><%= @jobb.salary %>">💶</a>
    <a href="#" data-container="body" data-toggle="popover" data-placement="left" style="top: 105px;
    left: 31px; position: absolute;" data-content="<h6><strong>Perspectives d'évolution:</strong></h6><%= @jobb.career %>">💼</a>
      <a href="#" data-container="body" data-toggle="popover" data-placement="left" style="top: 180px;
    left: 31px; position: absolute;" data-content="<h6><strong>Etudes:</strong></h6><%= @jobb.study %>">🎓</i></a>
  </div>
</div>


<script>
$(document).ready(function(){
    $('[data-toggle="popover"]').popover();
});
</script>


<%= render '/shared/navigationbar' %>