config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  devise_for :users, :controllers => {:registrations => "registrations"}
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :jobs, only: [ :index, :show ]
  get 'chooseajob', to: 'jobschoices#index', as: :jobschoices
  get 'chooseastudy', to: 'studieschoices#index', as: :studieschoices
  get 'autres_etudes', to: 'studieschoices#autres_etudes'
  get 'etudes_arts_et_design', to: 'studieschoices#etudes_arts_et_design'
  get 'batiment_et_travaux_publics', to: 'studieschoices#etudes_batiment_et_travaux_publics'
  get 'etudes_commerce_et_gestion', to: 'studieschoices#etudes_commerce_et_gestion'
  get 'etudes_droit', to: 'studieschoices#etudes_droit'
  get 'etudes_banque_et_assurance', to: 'studieschoices#etudes_banque_et_assurance'
  get 'etudes_environnement', to: 'studieschoices#etudes_environnement'
  get 'etudes_industrie', to: 'studieschoices#etudes_industrie'
  get 'etudes_communication_et_journalisme', to: 'studieschoices#etudes_communication_et_journalisme'
  get 'etudes_informatique_et_electronique', to: 'studieschoices#etudes_informatique_et_electronique'
  get 'etudes_medical_et_paramedical', to: 'studieschoices#etudes_medical_et_paramedical'
  get 'etudes_tourisme_hotellerie_et_restauration', to: 'studieschoices#etudes_tourisme_hotellerie_et_restauration'
  get 'etudes_specialisees', to: 'studieschoices#etudes_specialisees'
  get 'etudes_social_et_psychologie', to: 'studieschoices#etudes_social_et_psychologie'
  get 'etudes_ingenieur', to: 'studieschoices#etudes_ingenieur'
  patch "jobs/:id/like", to: "jobs#like", as: :like
  patch "jobs/:id/dislike", to: "jobs#dislike", as: :dislike
  get 'favorites', to: 'pages#favorites'
  get 'signupstudents', to: 'pages#signupstudents'
  get 'test', to: 'pages#test'
  get 'signupparents', to: 'pages#signupparents'
  get 'homepage', to: 'pages#homepage'
  get 'homepage_parents', to: 'pages#homepage_parents'
  get 'suggestion', to: 'pages#suggestion'
  get 'infos', to: 'pages#infos'
  get 'ose', to: 'pages#ose'
  get 'temoignage1', to: 'pages#temoignage1'
  get 'temoignage2', to: 'pages#temoignage2'
  get 'temoignage3', to: 'pages#temoignage3'
  get 'temoignage4', to: 'pages#temoignage4'
  get 'entretien', to: 'pages#entretien'
  get 'conseillers', to: 'pages#conseillers'
  get 'financements', to: 'pages#financements'
  get 'bourse', to: 'pages#bourse'
  get 'apl', to: 'pages#apl'
  get 'CGU', to: 'pages#CGU'
  get 'Mentions_legales', to: 'pages#Mentions_legales'
  get 'Contact', to: 'pages#Contact'
  get 'outils', to: 'pages#outils'
  get 'changements', to: 'pages#changements'
  get 'un_cv_parfait', to: 'pages#un_cv_parfait'
  get 'lettre_de_motivation_qui_cartonne', to: 'pages#lettre_de_motivation_qui_cartonne'
  get 'je_vais_tout_dechirer', to: 'pages#je_vais_tout_dechirer'
  get 'je_sors_du_lot', to: 'pages#je_sors_du_lot'
  get 'bourse_et_APL', to: 'pages#bourse_et_APL'
  get 'les_autres_aides', to: 'pages#les_autres_aides'
  get 'le_pret_bancaire', to: 'pages#le_pret_bancaire'
  get 'tout_savoir_sur_orientation', to: 'pages#tout_savoir_sur_orientation'
  get 'epanouissement_au_quotidien', to: 'pages#epanouissement_au_quotidien'
  get 'energies_que_je_transmets', to: 'pages#energies_que_je_transmets'
  get 'devenir_mentor', to: 'pages#devenir_mentor'
  get 'send_friend_request', to: 'networks#send_friend_request'
  get 'network', to: 'networks#network'
  get 'messenger', to: 'networks#messenger'
  get 'users_all', to: 'networks#users_all'
  get 'aideslogement', to: 'pages#aideslogement'
  get 'aidesregionales', to: 'pages#aidesregionales'
  get 'aidespourpartir', to: 'pages#aidespourpartir'
  get 'aidestransports', to: 'pages#aidestransports'
  get 'aidesmaster', to: 'pages#aidesmaster'
  get 'aidespremieremploi', to: 'pages#aidespremieremploi'
  get 'aidesartistes', to: 'pages#aidesartistes'
  get 'aidesmerite', to: 'pages#aidesmerite'
  get 'aidesurgences', to: 'pages#aidesurgences'
  get 'aidesautres', to: 'pages#aidesautres'
  get 'dropdown_HDF', to: 'pages#dropdown_HDF'
  get 'dropdown_IDF', to: 'pages#dropdown_IDF'
  get 'dropdown_Normandie', to: 'pages#dropdown_Normandie'
  get 'dropdown_Bretagne', to: 'pages#dropdown_Bretagne'
  get 'dropdown_PDLL', to: 'pages#dropdown_PDLL'
  get 'dropdown_CVDL', to: 'pages#dropdown_CVDL'
  get 'dropdown_BFC', to: 'pages#dropdown_BFC'
  get 'dropdown_GE', to: 'pages#dropdown_GE'
  get 'dropdown_NA', to: 'pages#dropdown_NA'
  get 'dropdown_ARA', to: 'pages#dropdown_ARA'
  get 'dropdown_Occitanie', to: 'pages#dropdown_Occitanie'
  get 'dropdown_PACA', to: 'pages#dropdown_PACA'
  get 'dropdown_Paradis_francais', to: 'pages#dropdown_Paradis_francais'

  resources :interests, only: [ :index, :show, :edit ]
  patch "interests/:id/likeinterest", to: "interests#likeinterest", as: :likeinterest
  patch "interests/:id/dislikeinterest", to: "interests#dislikeinterest", as: :dislikeinterest
  patch "interests/:id/like2interest", to: "interests#like2interest", as: :like2interest
  patch "interests/:id/dislike2interest", to: "interests#dislike2interest", as: :dislike2interest
  get 'meslikes', to: 'interests#meslikes'

  get 'myprofile', to: 'users#edit'
  patch 'edit_profile', to: 'users#update'
  get 'search', to: 'users#search'
  post 'unblock_friend', to: 'networks#unblock_friend'
  post 'accept_friend', to: 'networks#accept_friend'
  post 'decline_friend', to: 'networks#decline_friend'
  post 'request_friend', to: 'networks#request_friend'
  post 'block_friend', to: 'networks#block_friend'
  post 'remove_friend', to: 'networks#remove_friend'
  get 'search_friends', to: 'users#search_friends'

  resources :users do
    get :autocomplete_user_name, :on => :collection
  end

  resources :conversations do
    resources :messages
  end
end

app/models/interest.rb
class Interest < ApplicationRecord
  acts_as_votable
  has_many :job_interests
  has_many :jobs, through: :job_interests
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  before_action :authenticate_user!

  def index
    @interests = Interest.all - current_user.get_voted(Interest)
  end

  def edit
    @interests = current_user.get_voted(Interest)
  end

  def show
    @interest = Interest.find(params[:id])
  end

  def meslikes
    @interests = Interest.all
  end

  def likeinterest
    @interest = Interest.find(params[:id])
    @interest.liked_by current_user
    respond_to do |format|
      format.html { redirect_to interests_path }
      format.js
    end
  end

  def dislikeinterest
    @interest = Interest.find(params[:id])
    @interest.disliked_by current_user
    respond_to do |format|
      format.html { redirect_to interests_path }
      format.js
    end
  end
  def like2interest
    @interest = Interest.find(params[:id])
    @interest.liked_by current_user
    respond_to do |format|
      format.html { redirect_to interests_path }
      format.js
    end
  end

  def dislike2interest
    @interest = Interest.find(params[:id])
    @interest.disliked_by current_user
    respond_to do |format|
      format.html { redirect_to interests_path }
      format.js
    end
  end
end

app/views/interests/_card.html.erb
<div class="card2 card-likes" id= <%= "#{interest.id}" %>>
  <p><%= interest.name %></p>
  <% if interest.get_likes.where(voter_id: current_user).count == 0 %>
    <%= link_to like2interest_path(interest), method: :patch, remote: true, class: "card-like-link2" do%>
      <i class="far fa-heart"></i>
    <% end %>
  <% else %>
    <%= link_to dislike2interest_path(interest), method: :patch, remote: true, class: "card-like-link2" do %>
      <i class="fas fa-heart"></i>
    <% end %>
  <% end %>
</div>

app/views/interests/dislike2interest.js.erb
function refreshCard(outerHTML) {
  const interest = document.getElementById(<%= @interest.id %>);
  interest.outerHTML = outerHTML;
}

refreshCard('<%= j render "interests/card", interest:@interest %>');

app/views/interests/edit.html.erb
<div class="navbar-up">

    <% if user_signed_in? %>
      <div class="navbar-up-item">
        <i class=" back fas fa-chevron-left" onclick="history.back(-1)"></i>
        <a type="student-btn" href="/chooseajob" class="btn btn-primary next-step-btn-small">Etape 2: les métiers <i class="fas fa-arrow-right arrow-next-step"></i></a>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-up-item navbar-up-link" %>
    <% end %>
</div>
<div class="container">
  <div class="cards-interest">
    <% @interests.each do |interest| %>
      <div class="card-interest" data-interest-id="<%= interest.id %>">
        <div class="card-interest-content">
          <ul class="swipe-ul">
            <li class="swipe-li"><p><%= interest.name %></p>
            <%= link_to "", interest_path(interest), class: "card-link"%>
            <div class="remove-box-in-edit">
              <i class="fas fa-times"></i>
            </div>
            <% if interest.get_likes.where(voter_id: current_user).count == 0 %>
              <%= link_to likeinterest_path(interest), method: :patch, remote: true, class: "card-like-link" do%>
                <i class="far fa-heart"></i>
              <% end %>
            <% else %>
              <%= link_to dislikeinterest_path(interest), method: :patch, remote: true, class: "card-like-link" do %>
                <i class="fas fa-heart"></i>
              <% end %>
            <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= render '/shared/navigationbar' %>

app/views/interests/index.html.erb
<div class="navbar-up">
  <div class="navbar-up-item">
    <i class=" back fas fa-chevron-left" onclick="history.back(-1)"></i>
    <a type="student-btn" href="/chooseajob" class="btn btn-primary next-step-btn-small">Etape 2: les métiers <i class="fas fa-arrow-right arrow-next-step"></i></a>
  </div>
</div>
<div class="container-interests">
  <div class="cards-interest">
    <% @interests.each do |interest| %>
      <div class="card-interest" data-interest-id="<%= interest.id %>">
        <div class="card-interest-content">
          <ul class="swipe-ul">
            <li class="swipe-li"><p><%= interest.name %></p>
            <div class="remove-box">
              <i class="fas fa-times"></i>
            </div>
            <div class="like-box">
              <% if interest.get_likes.where(voter_id: current_user).count == 0 %>
                <%= link_to likeinterest_path(interest), method: :patch, remote: true, class: "card-like-link" do%>
                  <i class="far fa-heart"></i>
                <% end %>
              <% else %>
                <%= link_to dislikeinterest_path(interest), method: :patch, remote: true, class: "card-like-link" do %>
                  <i class="fas fa-heart"></i>
                <% end %>
              <% end %>
            </div>
            </li>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
  <div class="class-btn-likes"><a href="/meslikes" class="btn-likes">Modifier mes likes</a></div>
</div>

<script>
    function moveToLeft() {
      const buttons = document.querySelectorAll('.remove-box');
      if (buttons) {
        buttons.forEach((button) => {
          const card = button.parentElement.parentElement.parentElement.parentElement;
          button.addEventListener('click', () => {
            card.style.marginLeft = "-1400px";
          });
        });
      }
    }
    moveToLeft();
  </script>

<%= render '/shared/navigationbar' %>

app/views/interests/like2interest.js.erb
function refreshCard(outerHTML) {
  const interest = document.getElementById(<%= @interest.id %>);
  interest.outerHTML = outerHTML;
}

refreshCard('<%= j render "interests/card", interest:@interest %>');

app/views/interests/likeinterest.js.erb
function moveToRight() {
  const fullHeart = '<svg class="svg-inline--fa fa-heart fa-w-18" aria-hidden="true" data-prefix="fas" data-icon="heart" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" data-fa-i2svg=""><path fill="currentColor" d="M414.9 24C361.8 24 312 65.7 288 89.3 264 65.7 214.2 24 161.1 24 70.3 24 16 76.9 16 165.5c0 72.6 66.8 133.3 69.2 135.4l187 180.8c8.8 8.5 22.8 8.5 31.6 0l186.7-180.2c2.7-2.7 69.5-63.5 69.5-136C560 76.9 505.7 24 414.9 24z"></path></svg>'
  const card = document.querySelector('[data-interest-id="<%= @interest.id %>"]');
  const heart = card.querySelector('.fa-heart')
  heart.outerHTML = fullHeart;
  card.style.marginLeft = "1400px";
}

moveToRight();

app/views/interests/meslikes.html.erb
<div class="container-extra">

<div class="navbar-up">
  <div class="navbar-up-item">
    <i class=" back fas fa-chevron-left" onclick="history.back(-1)"></i>
    <a type="student-btn" href="/chooseajob" class="btn btn-primary next-step-btn-small">Etape 2: les métiers <i class="fas fa-arrow-right arrow-next-step"></i></a>
  </div>
</div>

<div class="container">
  <% if @interests.empty? %>
    <p class="text-error">Oups, il semblerait que tu n'aies pas encore liké de centres d'intérêt...</p>
      <div class="geek">🤓</div>
  <% else %>
  <div class="cards">
    <div class="row">
      <% @interests.each do |interest| %>
        <div class="col-xs-6 col-md-3">
          <div class="card2 card-likes" id= <%= "#{interest.id}" %>>
            <p><%= interest.name %></p>
            <% if interest.get_likes.where(voter_id: current_user).count == 0 %>
              <%= link_to like2interest_path(interest), method: :patch, remote: true, class: "card-like-link2" do%>
                <i class="far fa-heart"></i>
              <% end %>
            <% else %>
              <%= link_to dislike2interest_path(interest), method: :patch, remote: true, class: "card-like-link2" do %>
                <i class="fas fa-heart"></i>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <% end %>
</div>
</div>

<%= render '/shared/navigationbar' %>

app/views/interests/show.html.erb
<%= render 'shared/navbar' %>
<h1 class="interests"><%= @interest.name %></h1>